CREATE TABLE CLIENTES(
	ID_CLIENTE NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT pk_cliente PRIMARY KEY,
	NOMBRE VARCHAR(100),
	TELEFONO NUMBER,
	CORREO VARCHAR(30),
	USUARIO VARCHAR(25),
	FECHA_NACIMIENTO DATE NOT NULL
)